spring:
  datasource:
    url: jdbc:mysql://localhost:3306/students_db?useSSL=false
    username: root
    password: 36278

  jpa.hibernate.ddl_auto: update

logging:
  file: ./rest.log
  level:
    root: INFO

management:
  endpoints:
    web:
      exposure:
        include: prometheus
